#!/usr/bin/env python3
"""Sync skills catalog section in `skills/README.md` from public skills."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
README_FILE = SKILLS_DIR / "README.md"

START_MARKER = "<!-- BEGIN AUTO SKILLS -->"
END_MARKER = "<!-- END AUTO SKILLS -->"


@dataclass
class SkillEntry:
    name: str
    description: str
    rel_path: str


def is_public_skill(skill_md: Path) -> bool:
    rel_parts = skill_md.parent.relative_to(SKILLS_DIR).parts
    return not any(part.startswith("_") for part in rel_parts)


def parse_frontmatter(skill_md: Path) -> tuple[str, str]:
    text = skill_md.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return skill_md.parent.name, ""

    end = None
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            end = idx
            break
    if end is None:
        return skill_md.parent.name, ""

    metadata: dict[str, str] = {}
    for line in lines[1:end]:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip().strip('"').strip("'")

    name = metadata.get("name") or skill_md.parent.name
    description = metadata.get("description") or ""
    return name, description


def discover_skills() -> list[SkillEntry]:
    entries: list[SkillEntry] = []
    if not SKILLS_DIR.exists():
        return entries

    for skill_md in sorted(SKILLS_DIR.rglob("SKILL.md")):
        if not is_public_skill(skill_md):
            continue
        rel_path = skill_md.parent.relative_to(ROOT).as_posix()
        name, description = parse_frontmatter(skill_md)
        entries.append(
            SkillEntry(
                name=name,
                description=description,
                rel_path=rel_path,
            )
        )
    return entries


def render_catalog(entries: list[SkillEntry]) -> str:
    lines = [
        START_MARKER,
        "_Auto-generated by `scripts/sync_skills_readme.py` from public skills only. Do not edit manually._",
        "",
        "| Skill | Description | Path |",
        "| --- | --- | --- |",
    ]
    for entry in entries:
        desc = entry.description.replace("|", "\\|")
        lines.append(
            f"| `{entry.name}` | {desc} | [`{entry.rel_path}`](../{entry.rel_path}/SKILL.md) |"
        )
    lines.append(END_MARKER)
    return "\n".join(lines)


def sync_readme() -> int:
    if not README_FILE.exists():
        raise FileNotFoundError(f"Missing file: {README_FILE}")

    content = README_FILE.read_text(encoding="utf-8")
    generated = render_catalog(discover_skills())

    if START_MARKER in content and END_MARKER in content:
        start = content.index(START_MARKER)
        end = content.index(END_MARKER) + len(END_MARKER)
        updated = content[:start] + generated + content[end:]
    else:
        updated = content.rstrip() + "\n\n## Skill Catalog\n\n" + generated + "\n"

    if updated == content:
        print("skills README is up to date")
        return 0

    README_FILE.write_text(updated, encoding="utf-8")
    print("updated skills README catalog")
    return 0


if __name__ == "__main__":
    raise SystemExit(sync_readme())
